Repository sorocode/Dotox_FE, pull requests merged in 2024-08, with the labels that each got.

#29 Feat/issue 28 msw setting
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/components/common/StartWithGoogleButton.jsx
  src/components/common/StartWithNaverButton.jsx
  src/components/ui/Header.jsx
  src/main.jsx
  src/mocks/browser.js
  src/mocks/handlers.js
  src/mocks/mockData.js
  src/mocks/node.js
  src/pages/Login/LoginPage.jsx
  src/pages/Profile/ProfilePage.jsx
  src/pages/Recommend/RecommendPage.jsx
  src/store/store.js
  src/utils/axiosConfig.js
  src/utils/http.js
Labels: 📬 API, 🔨 Refactor, ✨ Feature

#30 Feat/issue 25 랭킹페이지 날짜 선택기능
  index.html
  src/components/ui/Header.jsx
  src/hooks/useCheckLogin.jsx
  src/pages/Index/IndexPage.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/Profile/ProfilePage.jsx
  src/pages/Ranking/CalendarBar.jsx
  src/pages/Ranking/DateItem.jsx
Labels: ✨ Feature

#38 Feat/http 로직 구성
  src/pages/Profile/ProfilePage.jsx
  src/utils/http.js
  vite.config.js
Labels: 📬 API

#41 [chore] Update README.md
  README.md
Labels: 📃 Docs

#47 Feat/issue 43 deploy
  Dockerfile
  nginx/nginx.conf
  vite.config.js
Labels: 🌏 Deploy

#48 수정완료
  src/assets/Line.png
  src/pages/Profile/ProfilePage.jsx
  src/pages/Quest/QuestDetail.jsx
  src/pages/Recommend/FindFriend.jsx
Labels: 🎨 Html&css

#50 중괄호 삭제
  src/pages/Profile/ProfilePage.jsx
Labels: 🐞 BugFix

#51 chore: Update RecommendPage.jsx to fix broken link
  src/pages/Recommend/FindFriend.jsx
  src/pages/Recommend/RecommendPage.jsx
Labels: 🐞 BugFix

#52 Feat/issue 37 시간측정기능
  src/components/common/TimerSection.jsx
  src/pages/Index/IndexPage.jsx
  src/utils/http.js
  src/utils/timer.js
Labels: 📬 API, ✨ Feature

#53 성격 유형별 관심사 추천
  src/pages/Recommend/InterestsArea.jsx
  src/pages/Recommend/SelectContainer.jsx
Labels: 🎨 Html&css
