Repository sorocode/Dotox_FE, pull requests merged in 2024-07, with the labels that each got.

#3 Bugfix/issue 2
  components.json
  src/components/ui/button.jsx
  src/components/ui/card.jsx
  src/components/ui/carousel.jsx
  src/components/ui/checkbox.jsx
  src/components/ui/dialog.jsx
  src/index.css
  tailwind.config.js
Labels: 🐞 BugFix

#8 Feat/issue 5 커스텀 버튼 추가
  src/components/pages/IndexPage.jsx
  src/components/ui/CustomButton.jsx
  src/components/ui/Header.jsx
  tailwind.config.js
Labels: 🎨 Html&css

#9 Feat/issue 4
  package-lock.json
  package.json
  src/assets/fakeImages/Profile1.svg
  src/assets/fakeImages/Profile2.svg
  src/assets/fakeImages/Profile3.svg
  src/assets/fakeImages/Profile4.svg
  src/assets/leftArrow.svg
  src/assets/rightArrow.svg
  src/components/pages/RankingPage.jsx
  src/components/ui/Ranking/CalendarBar.jsx
  src/components/ui/Ranking/DateItem.jsx
  src/components/ui/Ranking/RankingCard.jsx
  src/components/ui/Ranking/RecordArea.jsx
  src/components/ui/Ranking/RecordItem.jsx
  src/components/ui/Ranking/TopThreeArea.jsx
  src/components/ui/progress.jsx
  src/components/ui/skeleton.jsx
  src/main.jsx
  tailwind.config.js
  vite.config.js
Labels: 🎨 Html&css

#10 💄 로그인페이지 디자인
  public/KakaoSmall.png
  public/NaverCircle.png
  public/NaverLogin.png
  src/components/pages/LoginPage.jsx
  src/components/ui/Login/SimpleLoginContainer.jsx
  src/components/ui/LoginForm.jsx
  src/components/ui/separator.jsx
  src/store/store.js
Labels: 🎨 Html&css

#11 Feat/issue 6
  package-lock.json
  package.json
  src/assets/recommend1.png
  src/assets/recommend2.png
  src/components/pages/IndexPage.jsx
  src/components/pages/RecommendPage.jsx
  src/components/ui/LoginForm.jsx
  src/components/ui/Recommend/InterestItem.jsx
  src/components/ui/Recommend/InterestsArea.jsx
  src/components/ui/Recommend/SelectContainer.jsx
  src/components/ui/dropdown-menu.jsx
  src/components/ui/select.jsx
  tailwind.config.js
Labels: 🎨 Html&css

#14 Feat/issue 7
  src/assets/fakeImages/classImage.png
  src/assets/heart.svg
  src/assets/star.svg
  src/components/pages/IndexPage.jsx
  src/components/pages/RootLayout.jsx
  src/components/pages/StorePage.jsx
  src/components/ui/Store/CardContainer.jsx
  src/components/ui/Store/CardItem.jsx
  src/components/ui/badge.jsx
  src/components/ui/card.jsx
Labels: 🎨 Html&css

#16 chore: update CardContainer layout to use max-w-2xl class
  src/components/ui/Store/CardContainer.jsx
Labels: 🎨 Html&css

#18 feat: add Noto Sans KR font to extend fontFamily in tailwind.config.js
  tailwind.config.js
Labels: 🎨 Html&css

#19 취미 선택 페이지
  src/assets/rectangle520.png
  src/assets/rectangle521.png
  src/assets/rectangle522.png
  src/assets/rectangle523.png
  src/assets/rectangle524.png
  src/assets/rectangle5242.png
  src/assets/rectangle525.png
  src/assets/rectangle5252.png
  src/components/pages/IndexPage.jsx
  src/components/pages/QuestPage.jsx
  src/components/pages/SelectHobbiesPage.jsx
Labels: 🎨 Html&css

#22 Feat/issue 21 로그인 페이지 개선 및 로그인 상태에 따른 리다이렉팅
  public/NaverRectangle.png
  public/Profile1.svg
  src/components/common/Modal.jsx
  src/components/common/StartWithNaverButton.jsx
  src/components/pages/RankingPage.jsx
  src/components/ui/Header.jsx
  src/components/ui/LoginForm.jsx
  src/main.jsx
  src/pages/Index/IndexPage.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/Login/SimpleLoginContainer.jsx
  src/pages/Profile/ProfilePage.jsx
  src/pages/Profile/UserInfoSection.jsx
  src/pages/Quest/QuestPage.jsx
  src/pages/Ranking/CalendarBar.jsx
  src/pages/Ranking/DateItem.jsx
  src/pages/Ranking/RankingCard.jsx
  src/pages/Ranking/RankingPage.jsx
  src/pages/Ranking/RecordArea.jsx
  src/pages/Ranking/RecordItem.jsx
  src/pages/Ranking/TopThreeArea.jsx
  src/pages/Recommend/InterestItem.jsx
  src/pages/Recommend/InterestsArea.jsx
  src/pages/Recommend/RecommendPage.jsx
  src/pages/Recommend/SelectContainer.jsx
  src/pages/RootLayout.jsx
  src/pages/SelectHobbies/SelectHobbiesPage.jsx
  src/pages/Store/CardContainer.jsx
  src/pages/Store/CardItem.jsx
  src/pages/Store/StorePage.jsx
  src/utils/router.jsx
Labels: 🎨 Html&css, 🔨 Refactor, ✨ Feature

#26 23 feature 취미 추천 페이지모달
  public/SignGoogle.png
  public/brush.png
  public/flower.png
  public/muffin.png
  public/ring.png
  src/components/common/ConfirmModal.jsx
  src/components/common/StartWithGoogleButton.jsx
  src/hooks/useCheckLogin.jsx
  src/pages/Login/LoginPage.jsx
  src/pages/Profile/ProfilePage.jsx
  src/pages/Profile/UserInfoSection.jsx
  src/pages/Quest/QuestPage.jsx
  src/pages/Ranking/RankingPage.jsx
  src/pages/Recommend/RecommendPage.jsx
  src/pages/SelectHobbies/HobbyItem.jsx
  src/pages/SelectHobbies/RecommendModal.jsx
  src/pages/SelectHobbies/SelectHobbiesPage.jsx
  src/pages/Store/CardContainer.jsx
  src/pages/Store/CardItem.jsx
Labels: 🎨 Html&css, ✨ Feature
